print('Exercício Python 37: Escreva um programa em Python que leia um número inteiro qualquer e peça para o usuário escolher qual será a base de conversão: 1 para binário, 2 para octal e 3 para hexadecimal.')
print('-' * 30)
print('CONVERSOR DE BASES NUMÉRICAS')
print('-' * 30)
n = float(input('Digite o número que deseja converter:'))
print('Digite o numéro referente:')
convert = (int(input('Q')))